#ifndef GLOBALS_HPP
#define GLOBALS_HPP

#include <SFML/Window.hpp>

#define WINDOW_WIDTH sf::VideoMode::getDesktopMode().width
#define WINDOW_HEIGHT sf::VideoMode::getDesktopMode().height

// #define WINDOW_WIDTH 800
// #define WINDOW_HEIGHT 600

#define CAR_WIDTH 50.f
#define CAR_HEIGHT 80.f
#define CARS_DISTANCE_FROM_TOP WINDOW_HEIGHT * 0.6f

#define CAR_DEVIATION_FROM_MIDDLE 80.f

#define INITIAL_OBSTACLE_SPEED 6.f
#define OBSTACLE_TOP_SPEED_MULTIPLIER 2.f
#define OBSTACLE_WIDTH CAR_WIDTH
#define OBSTACLE_HEIGHT CAR_WIDTH

#define INITIAL_FOOD_SPEED INITIAL_OBSTACLE_SPEED
#define FOOD_WIDTH OBSTACLE_WIDTH
#define FOOD_HEIGHT OBSTACLE_HEIGHT
#define FOOD_TOP_SPEED_MULTIPLIER OBSTACLE_TOP_SPEED_MULTIPLIER

#define ENTITY_SPEED_MULTIPLIER 1.05f
#define ENTITY_START_HEIGHT 100.f

enum Lane
{
    LEFT,
    RIGHT
};

#endif // GLOBALS_HPP